---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  error = FALSE,
  message = FALSE,
  warning = FALSE,
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# lisr

<!-- badges: start -->

<!-- badges: end -->

R interface to the `Leipzig Informationssystem` ([LIS](https://statistik.leipzig.de/statserv/servod.aspx)).

## Installation

```{r installation, eval = FALSE}
remotes::install_github('nrkoehler/lisr')
```


## Usage

### Population

```{r pop-import}
library(lisr)
library(tidyverse)

df.POP <- get_lis_pop(rubrik_nr = 1) # inhabitants
df <- df.POP

```


```{r pop-glimpse}
glimpse(df)
df$KENNZIFFER
```


```{r pop-filter}
df.POP_sub <- df %>% 
  filter(KENNZIFFER == 'Bevölkerung insgesamt') %>% 
  select(-EINHEIT) %>% 
  mutate(KENNZIFFER = c('Estimate 1', 'Estimate 2', 'Estimate 3'))
df.sub <- df.POP_sub
```

```{r pop-long}
df.sub <- df.sub %>% 
  pivot_longer(cols = starts_with('JAHR'),
               names_to = 'Year',
               values_to = 'Inhabitants') %>% 
  mutate(Year = as.numeric(str_remove(Year, 'JAHR_')))
```


```{r pop-plot}
ggplot(df.sub, aes(x = Year, 
                       y = Inhabitants/1000,
                       colour = KENNZIFFER)) +
  geom_line() +
  geom_point() +
  scale_x_continuous(breaks = seq(2000, 2019, 2)) +
  scale_y_continuous(breaks = seq(480, 650, 10)) +
  theme_light() +
  theme(legend.position = 'bottom') +
  labs(colour = NULL,
       y = 'Inhabitants (1.000)',
       title = 'Population of Leipzig',
       subtitle = 'Number of inhabitants (2000 to 2019)',
       caption = 'Source: Leipzig Informationssystem, 2020')
```

### Housing

```{r housing-import}
df.HOUSING <- get_lis_housing(rubrik_nr = 3) # flat rents
df <- df.HOUSING
```

```{r housing-glimpse}
glimpse(df)
df$KENNZIFFER
```


```{r housing-filter}
df.HOUSING_sub <- df %>% 
  filter(KENNZIFFER == 'Haushalte insgesamt') %>% 
  mutate(KENNZIFFER = c('Estimate 1', 'Estimate 2'))
df.sub <- df.HOUSING_sub  
```

```{r housing-long}
df.sub <- df.sub %>% 
  pivot_longer(cols = starts_with('JAHR'),
               names_to = 'Year',
               values_to = 'Rent') %>% 
  mutate(Year = as.numeric(str_remove(Year, 'JAHR_')))
```


```{r housing-plot}
ggplot(df.sub, aes(x = Year, 
                       y = Rent,
                       colour = KENNZIFFER)) +
  geom_line() +
  geom_point() +
  scale_x_continuous(breaks = seq(2000, 2019, 2)) +
   scale_y_continuous(breaks = seq(4, 9, 1)) +
  theme_light() +
  theme(legend.position = 'bottom') +
  labs(colour = NULL,
       y = '€ / m²',
       title = 'Median rent in Leipzig',
       subtitle = '2000 to 2019',
       caption = 'Source: Leipzig Informationssystem, 2020')
```


### Weather

```{r weather-import}
df.WEATHER <- get_lis_geo(rubrik_nr = 3) # weather
df <- df.WEATHER %>% 
  select(-EINHEIT)
```

```{r weather-glimpse}
glimpse(df)
df$KENNZIFFER
```


```{r weather-filter}
df.WEATHER_sub <- df %>%
  filter(KENNZIFFER == "Lufttemperatur (Jahresmittel)" |
    KENNZIFFER == "Niederschlagshöhe (Jahressumme)") %>%
  mutate(KENNZIFFER = case_when(
    KENNZIFFER == "Lufttemperatur (Jahresmittel)" ~ "Temperature in °C (yearly mean)",
    KENNZIFFER == "Niederschlagshöhe (Jahressumme)" ~ "Rain in l (yearly sum)",
    TRUE ~ as.character(NA)
  ))
df.sub <- df.WEATHER_sub  
```

```{r weather-long}
df.sub <- df.sub %>% 
  pivot_longer(cols = starts_with('JAHR'),
               names_to = 'Year',
               values_to = 'Value') %>% 
  mutate(Year = as.numeric(str_remove(Year, 'JAHR_')))
```


```{r weather-plot}
ggplot(df.sub, aes(x = Year, 
                       y = Value)) +
  geom_step() +
  geom_point(colour = 'red3') +
  scale_x_continuous(breaks = seq(2000, 2019, 2)) +
  geom_smooth(method = 'lm') +
   # scale_y_continuous(breaks = seq(4, 9, 1)) +
  tidyquant::theme_tq() +
  theme(legend.position = 'bottom') +
  facet_wrap(.~KENNZIFFER, nrow = 2, scales = 'free') +
  labs(x = NULL,
       y = NULL,
       title = 'Temperature and rain in Leipzig',
       subtitle = '2000 to 2019',
       caption = 'Source: Leipzig Informationssystem, 2020')
```
