---
title: "The population of Leipzig"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{The population of Leipzig}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  error = FALSE,
  message = FALSE,
  warning = FALSE,
  collapse = TRUE,
  tidy = 'styler',
  fig.asp = 0.6,
  fig.width = 8,
  out.width = '100%',
  comment = "#>"
)
```

```{r setup}
library(lisr)
library(tidyverse)
```

```{r pop-import}
data <- get_lis_pop(rubrik_nr = 1) # inhabitants
```


```{r pop-variables}
colnames(data)
```

```{r pop-unit}
sum(!is.na(data$EINHEIT))

data <- data %>% 
  select(-EINHEIT)
```



```{r pop-kennziffer}
data$KENNZIFFER

```

```{r pop-labels}
data <- data %>% 
  mutate(QUELLE = c(rep('Statistisches Landesamtes Sachsen', 9), 
          rep('Leipizger Melderegister', 9),
          rep('Haupt- und Nebenwohnsitz', 9)),
         HERKUNFT = rep(c(rep('Gesamt', 3), 
                        rep('Deutsche', 3), 
                        rep('Ausländer', 3)), 3),
         KENNZIFFER = str_extract(KENNZIFFER, '^\\w+'),
         KENNZIFFER = str_replace(KENNZIFFER, paste(c('Deutsche', 'Ausländer'), collapse = '|'), 'Gesamt'),
         KENNZIFFER = paste(KENNZIFFER, HERKUNFT, sep = ': ')) %>% 
  relocate(QUELLE, KENNZIFFER) %>% 
  select(-HERKUNFT)
```



```{r pop-filter}
data.POP_sub <- data %>%
  filter(KENNZIFFER == "Bevölkerung: Gesamt") %>%
  mutate(KENNZIFFER = QUELLE)
data.sub <- data.POP_sub
```

```{r pop-long}
data.sub <- data.sub %>%
  pivot_longer(
    cols = starts_with("JAHR"),
    names_to = "Year",
    values_to = "Inhabitants"
  ) %>%
  mutate(Year = as.numeric(str_remove(Year, "JAHR_")))
```


```{r pop-plot}
ggplot(data.sub, aes(
  x = Year,
  y = Inhabitants / 1000,
  colour = KENNZIFFER
)) +
  geom_line() +
  geom_point() +
  scale_x_continuous(breaks = seq(2000, 2019, 2)) +
  scale_y_continuous(breaks = seq(480, 650, 20)) +
  hrbrthemes::theme_modern_rc() +
  theme(legend.position = "bottom") +
  labs(
    colour = NULL,
    y = "Inhabitants (1.000)",
    title = "Population of Leipzig",
    subtitle = "Number of inhabitants (2000 to 2019)",
    caption = "Source: Leipzig Informationssystem, 2020"
  )
```
