---
title: "Administrative area and weather"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Administrative area and weather}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  error = FALSE,
  message = FALSE,
  warning = FALSE,
  collapse = TRUE,
  tidy = 'styler',
  fig.asp = 0.6,
  fig.width = 8,
  out.width = '100%',
  comment = "#>"
)
```

```{r setup}
library(tidyverse)
library(lisr)
```


```{r weather-import}
data <- get_lis_geo(rubrik_nr = 3) # weather
```

```{r weather-names}
colnames(data)
```

```{r weather-kennziffer}
data$KENNZIFFER

```

```{r weather-filter}
data.sub <- data %>%
  filter(KENNZIFFER == "Lufttemperatur (Jahresmittel)" |
    KENNZIFFER == "Niederschlagshöhe (Jahressumme)") %>%
  mutate(KENNZIFFER = case_when(
    KENNZIFFER == "Lufttemperatur (Jahresmittel)" ~ "Temperature in °C (yearly mean)",
    KENNZIFFER == "Niederschlagshöhe (Jahressumme)" ~ "Rain in l (yearly sum)",
    TRUE ~ as.character(NA)
  ))

```

```{r weather-long}
data.sub <- data.sub %>%
  pivot_longer(
    cols = starts_with("JAHR"),
    names_to = "Year",
    values_to = "Value"
  ) %>%
  mutate(Year = as.numeric(str_remove(Year, "JAHR_")))
```


```{r weather-plot}
ggplot(data.sub, aes(
  x = Year,
  y = Value
)) +
  geom_step() +
  geom_point(colour = "red3") +
  scale_x_continuous(breaks = seq(2000, 2024, 2)) +
  geom_smooth(method = "loess") +
  tidyquant::theme_tq() +
  theme(legend.position = "bottom") +
  facet_wrap(. ~ KENNZIFFER, nrow = 2, scales = "free") +
  labs(
    x = NULL,
    y = NULL,
    title = "Temperature and rain in Leipzig",
    subtitle = "2000 to 2023",
    caption = "Source: Leipzig Informationssystem, 2024"
  )
```
